### ISSUE TITLE
Implement Design Support Library

### ISSUE THREAD

**Issue by jprberlin** [openHPI/android-app#4]
This could be achieved by using the new design support library

**Comment by rhlff** [comment]
Use CoordinatorLayout from Design Support Library: http://android-developers.blogspot.de/2015/05/android-design-support-library.html

**Comment by jprberlin** [comment]
@bjrne This is on your list, isnt it

**Comment by rhlff** [comment]
- [x] Use CoordinatorLayout
- [x] Make AppBar scrollable
- [x] Use TabLayout (see #22)

Implemented in [/feature/design-support](https://github.com/openHPI/android-app/tree/feature/design-support).

Known issues (hopefully fixed by Google soon):
- `WebView` doesn't support `NestedScrollView` or implements `NestedScrollingChild`, workaround is implemented with `NestedScrollWebView`. Scroll behavior isn't 100% perfect anymore with that, but it's acceptable.
- `EditText` in `NestedScrollWebView` with open keyboard blocks full scrolling. [#182362](https://code.google.com/p/android/issues/detail?id=182362)

**Comment by rhlff** [comment]
TODO:
- [ ] Change tab background in offline mode
- [ ] Make sure Cast MiniController widget is visible in all screens
